<?xml version="1.0"?>
<robot name="raspicat_wheel_gazebo" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="wheel_gazebo" params="prefix">
    <gazebo reference="${prefix}_wheel_link">
      <mu1>0.5</mu1>
      <mu2>0.5</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <maxVel>1.3</maxVel>
      <fdir1>1 0 0</fdir1>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="wheel_controller_gazebo" params="publish_tf publish_jointstate robot_namespace">
    <gazebo>
      <plugin name='differential_drive_controller' filename='libgazebo_ros_diff_drive.so'>
        <ros>
          <remapping>cmd_vel:=sim_cmd_vel</remapping>
          <remapping>odom:=odom</remapping>
        </ros>

        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2.0}</wheel_diameter>
        <max_wheel_torque>50</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_footprint</robot_base_frame>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>